"""Create Indixes

Revision ID: 876f7f93ef75
Revises: 333cadff2e7e
Create Date: 2025-09-04 00:40:00.926846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '876f7f93ef75'
down_revision: Union[str, Sequence[str], None] = '333cadff2e7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_index('ix_items_id_owner_id', 'items', ['id', 'owner_id'], unique=False)
    op.create_index(op.f('ix_items_owner_id'), 'items', ['owner_id'], unique=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_index(op.f('ix_items_owner_id'), table_name='items')
    op.drop_index('ix_items_id_owner_id', table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    # ### end Alembic commands ###
